# Generated by Django 4.1.3 on 2022-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_district_modifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='record',
        ),
        migrations.AddField(
            model_name='log',
            name='record_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='record_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
