# Generated by Django 4.1.3 on 2022-12-15 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_remove_log_record_log_record_id_log_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
