export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAIL = "RESET_FAIL";
export const FORGOT_SUCCESS = "FORGOT_SUCCESS";
export const FORGOT_FAIL = "FORGOT_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";
export const POST_COMMENT_REACTION_SUCCESS = "POST_COMMENT_REACTION_SUCCESS";
export const POST_COMMENT_REACTION_FAIL = "POST_COMMENT_REACTION_FAIL";
export const POST_REACTION_SUCCESS = "POST_REACTION_SUCCESS";
export const POST_REACTION_FAIL = "POST_REACTION_FAIL";

