# Generated by Django 4.1.3 on 2022-12-08 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.BigIntegerField()),
                ('reaction', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_post_reactions', to=settings.AUTH_USER_MODEL)),
                ('remover', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='removed_post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_reaction',
            },
        ),
        migrations.CreateModel(
            name='PostCommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.BigIntegerField()),
                ('reaction', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_post_comment_reactions', to=settings.AUTH_USER_MODEL)),
                ('remover', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='removed_post_comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_comment_reaction',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.BigIntegerField()),
                ('parent', models.BigIntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_post_comments', to=settings.AUTH_USER_MODEL)),
                ('remover', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='removed_post_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_comment',
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('category', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_post_categories', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_post_categories', to=settings.AUTH_USER_MODEL)),
                ('remover', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='removed_post_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_category',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=posts.models.user_directory_path)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('category', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_posts', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_posts', to=settings.AUTH_USER_MODEL)),
                ('remover', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='removed_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
