# Generated by Django 4.1.3 on 2022-12-14 13:18

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(null=True, validators=[django.core.validators.MinLengthValidator(256, 'body must contain at least 256 characters')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(128, 'description must contain at most 128 characters')]),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, validators=[django.core.validators.MaxLengthValidator(12, 'comment description must contain at most 12 characters')]),
        ),
    ]
