# Generated by Django 4.1.3 on 2022-12-15 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_postcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='posts.postcategory'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_post_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='remover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='removed_post_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
