# Generated by Django 4.1.3 on 2022-12-15 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_alter_post_body_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='remover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='removed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='remover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='removed_post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcommentreaction',
            name='remover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='removed_post_comment_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='remover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='removed_post_reactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
