# Generated by Django 4.1.3 on 2022-12-15 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postcomment_options_alter_postcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='description',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(12, 'comment description must contain at most 12 characters')]),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='posts.post'),
        ),
    ]
